export const DEFAULT_BORDER_COLOR = "#964B00";
export const BORDER_COLOR_UPDATE = "BORDER_COLOR_UPDATE";
export const TOGGLE_INSPECT = "TOGGLE_INSPECT";
export const GET_INSPECT_STATUS = "GET_INSPECT_STATUS";
